import unittest
import os
import tempfile
import io
from app import app, init_db, get_db_connection

class BlogFullTestSuite(unittest.TestCase):
    
    def setUp(self):
        """Runs before EACH test. Sets up a fresh temp database."""
        self.db_fd, app.config['DATABASE'] = tempfile.mkstemp()
        app.config['TESTING'] = True
        app.config['WTF_CSRF_ENABLED'] = False  # Disable CSRF for testing
        self.client = app.test_client()

        # Initialize the temp database structure
        with app.app_context():
            init_db()
            
        # Create a dummy user/admin session helper
        self.admin_username = "admin"
        self.admin_password = "password123"

    def tearDown(self):
        """Runs after EACH test. Cleans up the file."""
        os.close(self.db_fd)
        os.unlink(app.config['DATABASE'])

    # --- HELPER FUNCTIONS ---
    def login(self, username, password):
        return self.client.post('/login', data=dict(
            username=username,
            password=password
        ), follow_redirects=True)

    def logout(self):
        return self.client.get('/logout', follow_redirects=True)

    # --- TEST CASES ---

    def test_1_public_pages(self):
        """Test if normal users can see pages."""
        response = self.client.get('/')
        self.assertEqual(response.status_code, 200)
        
        response = self.client.get('/blog')
        self.assertEqual(response.status_code, 200)

    def test_2_admin_login(self):
        """Test login logic."""
        # 1. Try wrong password
        rv = self.login('admin', 'wrongpass')
        self.assertIn(b'Invalid Credentials', rv.data)

        # 2. Try correct password
        rv = self.login(self.admin_username, self.admin_password)
        # Check if we were redirected to blog (indicating success)
        self.assertEqual(rv.status_code, 200) 
        # Check if session is set (we can check via accessing a protected route)
        rv = self.client.get('/create_post')
        self.assertEqual(rv.status_code, 200) # Should be 200 OK (Allowed)

    def test_3_create_post(self):
        """Test creating a post (Requires Login)."""
        self.login(self.admin_username, self.admin_password)
        
        # Simulate image upload
        data = {
            'title': 'Automated Test Post',
            'content': 'This is generated by Python tests.',
            'image': (io.BytesIO(b"abcdef"), 'test.jpg') # Fake image file
        }
        
        rv = self.client.post('/create_post', data=data, content_type='multipart/form-data', follow_redirects=True)
        self.assertEqual(rv.status_code, 200)
        
        # Check if it appears in database
        conn = get_db_connection()
        post = conn.execute("SELECT * FROM posts WHERE title = 'Automated Test Post'").fetchone()
        conn.close()
        self.assertIsNotNone(post)

    def test_4_api_like_post(self):
        """Test the Swagger API: Like a Post."""
        # 1. Create a post first (manually in DB to save time)
        with app.app_context():
            conn = get_db_connection()
            conn.execute("INSERT INTO posts (title, content, date_posted, likes) VALUES ('API Test', 'C', '2023', 0)")
            conn.commit()
            conn.close()

        # 2. Hit the API (NOTE: Using /api/ prefix if you used the Blueprint fix)
        # If you didn't use the Blueprint fix, remove '/api' below.
        response = self.client.post('/api/like/1')
        
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json['likes'], 1)
        self.assertEqual(response.json['status'], 'success')

    def test_5_api_like_comment(self):
        """Test the Swagger API: Like a Comment."""
        # 1. Create post and comment
        with app.app_context():
            conn = get_db_connection()
            conn.execute("INSERT INTO posts (title, content, date_posted) VALUES ('P', 'C', 'D')")
            conn.execute("INSERT INTO comments (post_id, content, date_posted, likes) VALUES (1, 'Nice', 'D', 0)")
            conn.commit()
            conn.close()

        # 2. Hit the API
        response = self.client.post('/api/like_comment/1')
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json['likes'], 1)

    def test_6_delete_post(self):
        """Test Deleting a post."""
        # Setup: Create post, Login, then Delete
        with app.app_context():
            conn = get_db_connection()
            conn.execute("INSERT INTO posts (title, content, date_posted) VALUES ('To Delete', 'C', 'D')")
            conn.commit()
            conn.close()

        self.login(self.admin_username, self.admin_password)
        rv = self.client.get('/delete_post/1', follow_redirects=True)
        self.assertEqual(rv.status_code, 200)

        # Verify it's gone
        conn = get_db_connection()
        post = conn.execute("SELECT * FROM posts WHERE title = 'To Delete'").fetchone()
        conn.close()
        self.assertIsNone(post)

if __name__ == '__main__':
    print("Running Full System Tests...")
    unittest.main()