name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: input
    attributes:
      label: Page / Module
      placeholder: Home / About / Services / Admin
    validations:
      required: true

  - type: textarea
    attributes:
      label: Feature Description
      placeholder: Explain what needs to be built and why
    validations:
      required: true

  - type: textarea
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - Feature implemented
        - Responsive
        - Tested
